apiVersion: v1
kind: ConfigMap
metadata:
  name: cdx-notification-service-config
  namespace: cdx-production
  labels:
    app: cdx-notification-service
    component: notification-service
data:
  NODE_ENV: 'production'
  PORT: '3000'
  LOG_LEVEL: 'info'
  API_PREFIX: 'api/v1'

  # Database Configuration
  MONGODB_URI: 'mongodb://mongodb:27017/cdx_notification_service'
  MONGODB_DATABASE: 'cdx_notification_service'

  # Cache Configuration
  REDIS_HOST: 'redis'
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_PASSWORD: ''

  # Message Broker Configuration
  RABBITMQ_URL: 'amqp://guest:guest@rabbitmq:5672'
  RABBITMQ_QUEUE_PREFIX: 'cdx_notification'

  # Notification Service Configuration
  NOVU_API_KEY: ''
  NOVU_APP_ID: ''
  NOVU_BACKEND_URL: 'http://novu:3000'

  # Security Configuration
  JWT_SECRET: ''
  JWT_EXPIRES_IN: '24h'
  BCRYPT_ROUNDS: '12'

  # Rate Limiting
  RATE_LIMIT_TTL: '60'
  RATE_LIMIT_LIMIT: '100'

  # Health Check Configuration
  HEALTH_CHECK_TIMEOUT: '5000'
  HEALTH_CHECK_INTERVAL: '30000'

  # Monitoring Configuration
  ENABLE_METRICS: 'true'
  METRICS_PORT: '9090'
  ENABLE_TRACING: 'true'
  JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
---
apiVersion: v1
kind: Secret
metadata:
  name: cdx-notification-service-secrets
  namespace: cdx-production
  labels:
    app: cdx-notification-service
    component: notification-service
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  MONGODB_PASSWORD: '' # base64 encoded
  REDIS_PASSWORD: '' # base64 encoded
  RABBITMQ_PASSWORD: '' # base64 encoded
  NOVU_API_KEY: '' # base64 encoded
  JWT_SECRET: '' # base64 encoded
  ENCRYPTION_KEY: '' # base64 encoded
