apiVersion: v1
kind: ServiceMonitor
metadata:
  name: cdx-notification-service-monitor
  namespace: cdx-production
  labels:
    app: cdx-notification-service
    component: notification-service
spec:
  selector:
    matchLabels:
      app: cdx-notification-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cdx-notification-service-alerts
  namespace: cdx-production
  labels:
    app: cdx-notification-service
    component: notification-service
spec:
  groups:
    - name: cdx-notification-service
      rules:
        - alert: NotificationServiceDown
          expr: up{job="cdx-notification-service"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: 'Notification Service is down'
            description: 'CDX Notification Service has been down for more than 1 minute'

        - alert: HighErrorRate
          expr: rate(http_requests_total{job="cdx-notification-service",status=~"5.."}[5m]) > 0.1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: 'High error rate in Notification Service'
            description: 'Error rate is {{ $value }} errors per second'

        - alert: HighResponseTime
          expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="cdx-notification-service"}[5m])) > 2
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: 'High response time in Notification Service'
            description: '95th percentile response time is {{ $value }} seconds'

        - alert: HighMemoryUsage
          expr: (container_memory_usage_bytes{job="cdx-notification-service"} / container_spec_memory_limit_bytes{job="cdx-notification-service"}) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: 'High memory usage in Notification Service'
            description: 'Memory usage is {{ $value | humanizePercentage }}'

        - alert: HighCPUUsage
          expr: (rate(container_cpu_usage_seconds_total{job="cdx-notification-service"}[5m]) / container_spec_cpu_quota{job="cdx-notification-service"}) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: 'High CPU usage in Notification Service'
            description: 'CPU usage is {{ $value | humanizePercentage }}'
