apiVersion: v1
kind: Namespace
metadata:
  name: cdx-production
  labels:
    name: cdx-production
    environment: production
    project: cdx
  annotations:
    description: 'CDX Production Environment'
    contact: 'devops@cdx.com'
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cdx-production-quota
  namespace: cdx-production
spec:
  hard:
    requests.cpu: '4'
    requests.memory: 8Gi
    limits.cpu: '8'
    limits.memory: 16Gi
    pods: '20'
    services: '10'
    secrets: '20'
    configmaps: '20'
    persistentvolumeclaims: '5'
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cdx-production-limits
  namespace: cdx-production
spec:
  limits:
    - default:
        cpu: '500m'
        memory: '512Mi'
      defaultRequest:
        cpu: '100m'
        memory: '128Mi'
      type: Container
    - max:
        cpu: '2'
        memory: '4Gi'
      min:
        cpu: '50m'
        memory: '64Mi'
      type: Container
